services:
  - type: web
    name: bashaer-pharmacy
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-ara
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bashaer-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: bashaer-db
    plan: free
